#pragma once

#include <array>

#include "Species.h"
#include "World.h"

namespace Gargantua {

/**
 * The caverns.
 *
 * GENERATED by tools/export-world-cpp.mjs in the browser build. Do not hand
 * edit: change the layout there, where `npm run content` verifies that every
 * marker is reachable and every doorway has one pointing back, and export again.
 *
 * Three caverns in a chain rather than a hub. The Reach drops into the Deep,
 * and the Deep into the Vault. Each is harder than the last and holds slugs the
 * ones above it do not, so going deeper is how a blaster fills out.
 */

// The Hollow Reach — 2000x1500
inline constexpr std::array<Rect, 32> HollowReachWalls{{
    {0.0f, 0.0f, 2000.0f, 40.0f},
    {0.0f, 1460.0f, 2000.0f, 40.0f},
    {0.0f, 0.0f, 40.0f, 1500.0f},
    {1960.0f, 0.0f, 40.0f, 1500.0f},
    {560.0f, 40.0f, 40.0f, 140.0f},
    {560.0f, 380.0f, 40.0f, 280.0f},
    {560.0f, 860.0f, 40.0f, 250.0f},
    {560.0f, 1310.0f, 40.0f, 150.0f},
    {1200.0f, 40.0f, 40.0f, 300.0f},
    {1200.0f, 540.0f, 40.0f, 620.0f},
    {1200.0f, 1360.0f, 40.0f, 100.0f},
    {40.0f, 520.0f, 100.0f, 40.0f},
    {340.0f, 520.0f, 520.0f, 40.0f},
    {1060.0f, 520.0f, 500.0f, 40.0f},
    {1760.0f, 520.0f, 200.0f, 40.0f},
    {40.0f, 980.0f, 300.0f, 40.0f},
    {540.0f, 980.0f, 200.0f, 40.0f},
    {940.0f, 980.0f, 470.0f, 40.0f},
    {1610.0f, 980.0f, 350.0f, 40.0f},
    {150.0f, 120.0f, 90.0f, 90.0f},
    {760.0f, 160.0f, 100.0f, 100.0f},
    {980.0f, 300.0f, 120.0f, 80.0f},
    {1400.0f, 120.0f, 140.0f, 90.0f},
    {1700.0f, 260.0f, 110.0f, 110.0f},
    {100.0f, 720.0f, 100.0f, 100.0f},
    {820.0f, 680.0f, 80.0f, 80.0f},
    {960.0f, 800.0f, 80.0f, 80.0f},
    {1350.0f, 660.0f, 120.0f, 100.0f},
    {1700.0f, 800.0f, 140.0f, 90.0f},
    {140.0f, 1180.0f, 120.0f, 120.0f},
    {860.0f, 1180.0f, 100.0f, 100.0f},
    {1600.0f, 1150.0f, 130.0f, 130.0f},
}};

inline constexpr std::array<Encounter, 5> HollowReachEncounters{{
    {"hr-ore-gallery", SpeciesId::Mirebubble, 920.0f, 200.0f},
    {"hr-kiln-shelf", SpeciesId::Gritmaw, 1750.0f, 170.0f},
    {"hr-dripstone", SpeciesId::Thornwhistle, 300.0f, 830.0f},
    {"hr-quiet-pools", SpeciesId::Dewspine, 300.0f, 1350.0f},
    {"hr-deep-sink", SpeciesId::Bramblehusk, 1700.0f, 1380.0f},
}};

inline constexpr std::array<Trainer, 3> HollowReachTrainers{{
    {"hr-wick", "Wick", "Lamp-Tender",
     {SpeciesId::Cinderling, SpeciesId::Voltmote, SpeciesId::Thornwhistle, SpeciesId::None, SpeciesId::None}, 3, 2,
     "You are the one who has been waking my slugs up. Fine — show me what you have been teaching them.",
     "That was a better order than I had. Take the Rimeclutch; it never did listen to me anyway.",
     "No shame in it. Go and catch a few more, then come back and we will do this again.",
     SpeciesId::Rimeclutch, 760.0f, 1240.0f},
    {"hr-odell", "Odell Vane", "Ore-Runner",
     {SpeciesId::Gritmaw, SpeciesId::Mirebubble, SpeciesId::Pyrelash, SpeciesId::Skirlwing, SpeciesId::None}, 4, 4,
     "I run ore through these passages eight hours a day and I have never once been stopped. Try.",
     "Stopped. Huh. Here — the Pyrelash has been waiting for somebody who can aim it.",
     "Still running. Come back when your team has a second idea in it.",
     SpeciesId::Pyrelash, 1560.0f, 700.0f},
    {"hr-quarrel", "Sister Quarrel", "Cavern Warden",
     {SpeciesId::Nullmoth, SpeciesId::Glimmerquill, SpeciesId::Rimeclutch, SpeciesId::Voltmote, SpeciesId::Dewspine}, 5, 6,
     "I have held the Reach for eleven years. Every slinger who walks out of here walks past me first.",
     "Eleven years. Well. The Glimmerquill goes to whoever can catch it, and today that is you.",
     "Close. Closer than most. Fill out that blaster and find me again — I am not going anywhere.",
     SpeciesId::Glimmerquill, 1500.0f, 1200.0f},
}};

inline constexpr std::array<Exit, 1> HollowReachExits{{
    {"hr-to-kindled", {1790.0f, 570.0f, 120.0f, 120.0f}, "kindled-deep", {240.0f, 760.0f}, "Down to the Kindled Deep"},
}};

inline constexpr std::array<Point, 11> HollowReachPassages{{
    {580.0f, 280.0f},
    {580.0f, 760.0f},
    {580.0f, 1210.0f},
    {1220.0f, 440.0f},
    {1220.0f, 1260.0f},
    {240.0f, 540.0f},
    {960.0f, 540.0f},
    {1660.0f, 540.0f},
    {440.0f, 1000.0f},
    {840.0f, 1000.0f},
    {1510.0f, 1000.0f},
}};

inline constexpr Biome HollowReach{
    "hollow-reach", "The Hollow Reach",
    "The first cavern under Gargantua. Cold air, ore light, and something moving in the side passages.",
    {0.0f, 0.0f, 2000.0f, 1500.0f},
    HollowReachWalls.data(), 32,
    HollowReachEncounters.data(), 5,
    HollowReachTrainers.data(), 3,
    HollowReachExits.data(), 1,
    HollowReachPassages.data(), 11,
    Mood::Stone,
};

// The Kindled Deep — 2200x1600
inline constexpr std::array<Rect, 27> KindledDeepWalls{{
    {0.0f, 0.0f, 2200.0f, 40.0f},
    {0.0f, 1560.0f, 2200.0f, 40.0f},
    {0.0f, 0.0f, 40.0f, 1600.0f},
    {2160.0f, 0.0f, 40.0f, 1600.0f},
    {620.0f, 40.0f, 120.0f, 640.0f},
    {620.0f, 560.0f, 380.0f, 120.0f},
    {1220.0f, 560.0f, 300.0f, 120.0f},
    {1400.0f, 560.0f, 120.0f, 700.0f},
    {620.0f, 1140.0f, 900.0f, 120.0f},
    {40.0f, 400.0f, 340.0f, 40.0f},
    {300.0f, 1180.0f, 320.0f, 40.0f},
    {1000.0f, 40.0f, 40.0f, 260.0f},
    {1700.0f, 40.0f, 40.0f, 280.0f},
    {1520.0f, 700.0f, 420.0f, 40.0f},
    {1780.0f, 1140.0f, 380.0f, 40.0f},
    {200.0f, 120.0f, 100.0f, 90.0f},
    {430.0f, 520.0f, 90.0f, 90.0f},
    {120.0f, 980.0f, 110.0f, 100.0f},
    {1180.0f, 140.0f, 120.0f, 100.0f},
    {1500.0f, 300.0f, 110.0f, 110.0f},
    {900.0f, 760.0f, 110.0f, 100.0f},
    {1240.0f, 980.0f, 100.0f, 100.0f},
    {1880.0f, 180.0f, 120.0f, 110.0f},
    {1520.0f, 1000.0f, 130.0f, 100.0f},
    {400.0f, 1440.0f, 130.0f, 120.0f},
    {900.0f, 1440.0f, 140.0f, 120.0f},
    {1300.0f, 1260.0f, 120.0f, 100.0f},
}};

inline constexpr std::array<Encounter, 3> KindledDeepEncounters{{
    {"kd-coldmouth", SpeciesId::Chillblain, 420.0f, 200.0f},
    {"kd-crucible", SpeciesId::Slagmaw, 1160.0f, 900.0f},
    {"kd-flue", SpeciesId::Voltmote, 860.0f, 220.0f},
}};

inline constexpr std::array<Trainer, 1> KindledDeepTrainers{{
    {"kd-tallow", "Hob Tallow", "Slag-Walker",
     {SpeciesId::Slagmaw, SpeciesId::Cinderling, SpeciesId::Voltmote, SpeciesId::Chillblain, SpeciesId::None}, 4, 5,
     "I walk the edge of that channel barefoot, most days. So understand me before you start: I do not hurry, and I do not get burned.",
     "Hurried me anyway. Go on, take the Gallowspark — it has been earthing itself through my own slugs for a month and I am tired of it.",
     "The heat gets everybody on their first way down. Cool off, put a second idea in that blaster, and walk the channel back round to me.",
     SpeciesId::Gallowspark, 1720.0f, 900.0f},
}};

inline constexpr std::array<Exit, 2> KindledDeepExits{{
    {"kd-to-hollow", {110.0f, 560.0f, 140.0f, 140.0f}, "hollow-reach", {1850.0f, 1150.0f}, "Back up to The Hollow Reach"},
    {"kd-to-vault", {1960.0f, 940.0f, 140.0f, 140.0f}, "drowned-vault", {300.0f, 300.0f}, "Down to the Drowned Vault"},
}};

inline constexpr std::array<Point, 8> KindledDeepPassages{{
    {500.0f, 420.0f},
    {170.0f, 1200.0f},
    {680.0f, 910.0f},
    {1110.0f, 620.0f},
    {1020.0f, 400.0f},
    {1720.0f, 440.0f},
    {2050.0f, 720.0f},
    {1650.0f, 1160.0f},
}};

inline constexpr Biome KindledDeep{
    "kindled-deep", "The Kindled Deep",
    "One floor under the Reach. The rock is warm through your boots, the channel throws more light than your lamp does, and nothing down here is asleep.",
    {0.0f, 0.0f, 2200.0f, 1600.0f},
    KindledDeepWalls.data(), 27,
    KindledDeepEncounters.data(), 3,
    KindledDeepTrainers.data(), 1,
    KindledDeepExits.data(), 2,
    KindledDeepPassages.data(), 8,
    Mood::Molten,
};

// The Drowned Vault — 2400x1700
inline constexpr std::array<Rect, 35> DrownedVaultWalls{{
    {0.0f, 0.0f, 2400.0f, 40.0f},
    {0.0f, 1660.0f, 2400.0f, 40.0f},
    {0.0f, 0.0f, 40.0f, 1700.0f},
    {2360.0f, 0.0f, 40.0f, 1700.0f},
    {660.0f, 40.0f, 40.0f, 120.0f},
    {660.0f, 400.0f, 40.0f, 160.0f},
    {1620.0f, 40.0f, 40.0f, 220.0f},
    {1620.0f, 500.0f, 40.0f, 60.0f},
    {40.0f, 560.0f, 140.0f, 40.0f},
    {400.0f, 560.0f, 740.0f, 40.0f},
    {1360.0f, 560.0f, 600.0f, 40.0f},
    {2180.0f, 560.0f, 180.0f, 40.0f},
    {1000.0f, 760.0f, 440.0f, 240.0f},
    {40.0f, 1160.0f, 200.0f, 40.0f},
    {460.0f, 1160.0f, 1040.0f, 40.0f},
    {1720.0f, 1160.0f, 640.0f, 40.0f},
    {1000.0f, 1200.0f, 40.0f, 180.0f},
    {1000.0f, 1600.0f, 40.0f, 60.0f},
    {180.0f, 700.0f, 300.0f, 240.0f},
    {600.0f, 960.0f, 220.0f, 120.0f},
    {1700.0f, 760.0f, 340.0f, 220.0f},
    {1800.0f, 260.0f, 260.0f, 200.0f},
    {260.0f, 1300.0f, 320.0f, 200.0f},
    {1560.0f, 1320.0f, 360.0f, 200.0f},
    {420.0f, 380.0f, 90.0f, 90.0f},
    {900.0f, 380.0f, 100.0f, 80.0f},
    {1420.0f, 120.0f, 90.0f, 90.0f},
    {2180.0f, 160.0f, 110.0f, 110.0f},
    {860.0f, 660.0f, 80.0f, 80.0f},
    {300.0f, 1020.0f, 90.0f, 90.0f},
    {1520.0f, 680.0f, 80.0f, 80.0f},
    {2180.0f, 1000.0f, 100.0f, 100.0f},
    {760.0f, 1440.0f, 90.0f, 90.0f},
    {1120.0f, 1300.0f, 80.0f, 80.0f},
    {2080.0f, 1300.0f, 100.0f, 100.0f},
}};

inline constexpr std::array<Encounter, 3> DrownedVaultEncounters{{
    {"dv-lantern-walk", SpeciesId::Wispwick, 1200.0f, 240.0f},
    {"dv-west-pool", SpeciesId::Brinemoth, 560.0f, 820.0f},
    {"dv-apse", SpeciesId::Nullmoth, 1200.0f, 1560.0f},
}};

inline constexpr std::array<Trainer, 1> DrownedVaultTrainers{{
    {"dv-fen", "Sable Fen", "Vault-Keeper",
     {SpeciesId::Nullmoth, SpeciesId::Glimmerquill, SpeciesId::Wispwick, SpeciesId::Brinemoth, SpeciesId::Rimeclutch}, 5, 8,
     "Nothing down here needs a lamp any more — the light grows on its own, and so does everything else. Let us see what you have grown.",
     "So the water lets somebody through at last. Take the Hollowfang; it has been biting holes in my dark for years and I have never once been able to follow it.",
     "Do not walk back up on my account. Sit, dry off, and look again at the order you sent them in — that was the only thing wrong with it. The water is not going anywhere, and neither am I.",
     SpeciesId::Hollowfang, 2200.0f, 1520.0f},
}};

inline constexpr std::array<Exit, 1> DrownedVaultExits{{
    {"dv-to-kindled", {100.0f, 100.0f, 150.0f, 150.0f}, "kindled-deep", {1700.0f, 1200.0f}, "Back up to The Kindled Deep"},
}};

inline constexpr std::array<Point, 8> DrownedVaultPassages{{
    {680.0f, 280.0f},
    {1640.0f, 380.0f},
    {290.0f, 580.0f},
    {1250.0f, 580.0f},
    {2070.0f, 580.0f},
    {350.0f, 1180.0f},
    {1610.0f, 1180.0f},
    {1020.0f, 1490.0f},
}};

inline constexpr Biome DrownedVault{
    "drowned-vault", "The Drowned Vault",
    "The last cavern, and the wettest. Still water, halls somebody built, and a light down here that grows instead of burns.",
    {0.0f, 0.0f, 2400.0f, 1700.0f},
    DrownedVaultWalls.data(), 35,
    DrownedVaultEncounters.data(), 3,
    DrownedVaultTrainers.data(), 1,
    DrownedVaultExits.data(), 1,
    DrownedVaultPassages.data(), 8,
    Mood::Drowned,
};

/** Every cavern, in the order you meet them. */
inline constexpr std::array<const Biome*, 3> AllBiomes{{
    &HollowReach,
    &KindledDeep,
    &DrownedVault,
}};

/** Where a new slinger starts. */
inline constexpr const Biome& FirstBiome = HollowReach;

inline constexpr const Biome* FindBiome(std::string_view Id) {
    for (const Biome* B : AllBiomes) {
        if (B->Id == Id) {
            return B;
        }
    }
    return nullptr;
}

}  // namespace Gargantua
